baseURL: http://ryantuck.io/
languageCode: en-us
title: Ryan Tuck
theme: codex

params:
  github: "https://github.com/ryantuck"
  twitter: "https://twitter.com/ryntck"

menu:
  main:

    - identifier: /
      name: /
      title: /
      url: /
      weight: 1

    - identifier: roam
      name: roam
      weight: 10
      url: /notes/roam

    - identifier: notes
      name: notes
      weight: 100
      url: /notes/start

