baseURL: http://ryantuck.io/
languageCode: en-us
title: Ryan Tuck
theme: codex

params:
  github: "https://github.com/ryantuck"
  twitter: "https://twitter.com/ryntck"

menu:
  main:

    - identifier: /
      name: /
      title: /
      url: /

    - identifier: notes
      name: notes
      url: /notes/start
