baseURL = "http://ryantuck.io/"
languageCode = "en-us"
title = "Ryan Tuck"
theme = "codex"

[params]
  github = "https://github.com/ryantuck"
  twitter = "https://twitter.com/ryntck"

[[menu.main]]
    identifier = "/"
    name = "/"
    title = "/"
    url = "/"

[[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume.pdf"
