site_name: Ryan Tuck

# navigiation, no breathin
nav:
  - home: index.md
  - ideas: ideas.md
  - tech notes:
    - new machine: new_machine.md
    - git: git.md
    - telnet: telnet.md
    - vim: vim.md
    - s3 site: s3_site.md
  - lists:
    - karaoke: karaoke.md
    - groceries: groceries.md
    - links: links.md
  - more:
    - mtg arena on aws: mtg-arena-on-aws.md
    - hot sauce: hotsauce.md
    - nyc: nyc.md

theme:
  name: material
  palette:
    primary: 'black'
    accent: 'green'
  logo:
    # more here: https://material.io/resources/icons/
    icon: 'cloud_queue'
  favicon: 'img/self.png'
  font:
    text: 'Roboto Mono'
    code: 'Roboto Mono'

repo_name: 'ryantuck/ryantuck.io'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/ryantuck'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/users/1700270/ryan-tuck'
    - type: 'twitter'
      link: 'https://twitter.com/ryntck'
    - type: 'instagram'
      link: 'https://instagram.com/ryntck'
# disable editing
edit_uri: ''

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown



